name: .NET
on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.201
      - name: Install dependencies
        run: dotnet restore UniverseSharp
      - name: Build
        run: dotnet build UniverseSharp --configuration Release --no-restore
      - name: Test
        run: dotnet test UniverseSharp.Tests